Av 1435 new dataset page
vrk-kpa/opendata pull request #1270
Opened 2021-08-05 12:30 UTC by beazil

https://github.com/ckan/ckanext-spatial/pull/254 needs to merged with this

2021-08-17 05:33 UTC, Zharktas requested changes
Changing the order in schema file dataset.json actually also reorders the form which is already designed to be in specific order. So that shouldn't be done unless there is some reason for it which I don't remember just now.

2021-08-17 05:33 UTC, Zharktas commented on modules/ckanext-ytp_main/ckanext/ytp/templates/package/snippets/dataset_map_sidebar.html
> +    </section>
This file could be named templates/spatial/snippets/dataset_map_sidebar.html and it should pick it up, if it doesn't plugin order might need to be changed.

2021-09-06 05:54 UTC, beazil commented on modules/ckanext-ytp_main/ckanext/ytp/templates/scheming/package/snippets/additional_info.html
>            field=field, data=pkg_dict, schema=schema -%}</td>
`field=field` should be changed to `field=field[0]`

2021-09-06 06:34 UTC, Zharktas approved these changes

2021-09-06 07:25 UTC, merged